feat: INFRA-403 Refactored openstack etcd module to take advantage of…
Ferlab-Ste-Justine/terraform-openstack-etcd-server pull request #1
Opened 2023-07-12 11:28 UTC by Magnitus-

… all the improvements we made in its libvirt counterpart and also to remove namespace argument and add server group

2023-07-18 17:55 UTC, sebastienbonami requested changes

2023-07-18 17:55 UTC, sebastienbonami commented on README.md
Missed `metrics` in variable `fluentbit`. Also, the second `enabled`, `source`, `etcd` and `git` that are under `fluentbit` should be under `fluentbit_dynamic_config`.

2023-07-18 17:55 UTC, sebastienbonami commented on versions.tf
I recommend adding `hashicorp/cloudinit` with a version constraint, otherwise the latest version will always be taken (and we could face issues in the future).

2023-07-27 22:13 UTC, Magnitus- commented on versions.tf
Given that modules share providers, we always put as wide a range as possible, otherwise we get stuck in upgrade hell where we have to solve conflicting provider expectations.

For that reason, I tend to lock a narrow version of providers in the pipeline itself, not in each module, though if I know that a module is incompatible with a provider outside a certain version range, I would definitely restrict it to the versions that are compatible.

2023-07-27 22:23 UTC, Magnitus- commented on versions.tf
Ah, I see. Its not just the version constraint. I'm also putting the wrong provider in the dependencies. This, I should address.

2023-07-27 22:29 UTC, Magnitus- commented on versions.tf
I thought about it quickly. I guess I'll put it at the major version and trust hashicorp to honor semver here.

2023-07-27 22:35 UTC, Magnitus- commented on README.md
It was a syntax error in the markdown ><: https://github.com/Ferlab-Ste-Justine/openstack-etcd-server/commit/0c5bd434a0f7559d8626b37a12206e968be2a639

Thanks.

2023-07-28 02:57 UTC, merged